{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<table width="100%" cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td valign="top">
            <p>
                <b>{"Customer"|i18n("design/standard/shop")}</b>
            </p>
            <p>
                {foreach $order.account_information.field_list.customer as $field}
                    {$order.account_information.field_configuration.$field.name}: {$order.account_information.account_info.$field|wash}<br />
                {/foreach}
            </p>

        </td>
        <td valign="top">

            <p>
                <b>{"Address"|i18n("design/standard/shop")}</b>
            </p>
            <p>
                {foreach $order.account_information.field_list.delivery_address as $field}
                    {$order.account_information.field_configuration.$field.name}: {$order.account_information.account_info.$field|wash}<br />
                {/foreach}
            </p>
        </td>
    </tr>
</table>

{if $order.account_information.comment}
    <p>
        <b>{'Comment'|i18n( 'design/standard/shop' )}</b>
    </p>
    <p>
        {$order.account_information.comment|wash|nl2br}
    </p>
{/if}
