{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{"Your account information"|i18n("design/standard/shop")}</h1>

{if $input_error}
    <div class="warning">
        <p>
            {"Input did not validate, all fields marked with * must be filled in"|i18n("design/standard/shop")}
        </p>
    </div>

{/if}
<form method="post" action={"/owshop/userregister/"|ezurl}>
    <div class="block">
        <label>
            <input type="radio" name="DeliveryAddress" value="UserAccountAddress" checked="checked">
            {"Deliver to this address"|i18n("design/standard/shop")}
        </label>
        {if or($delivery_address_field_list['FirstName'], $delivery_address_field_list['LastName'])}
            <p class="user-name">
                {$delivery_address_field_list['FirstName']['UserAccountValue']}
                {$delivery_address_field_list['LastName']['UserAccountValue']}
            </p>
        {/if}
        {if $delivery_address_field_list['Street1']}
            <p class="user-address-street1">
                {$delivery_address_field_list['Street1']['UserAccountValue']}
            </p>
        {/if}
        {if $delivery_address_field_list['Street2']}
            <p class="user-address-street2">
                {$delivery_address_field_list['Street2']['UserAccountValue']}
            </p>
        {/if}
        {if or($delivery_address_field_list['Zip'], $delivery_address_field_list['Place'])}
            <p class="user-address-place">
                {$delivery_address_field_list['Zip']['UserAccountValue']}
                {$delivery_address_field_list['Place']['UserAccountValue']}
            </p>
        {/if}
        {if $delivery_address_field_list['State']}
            <p class="user-address-state">
                {$delivery_address_field_list['State']['UserAccountValue']}
            </p>
        {/if}
        {if $delivery_address_field_list['Country']}
            <p class="user-address-country">
                {$delivery_address_field_list['Country']['UserAccountValue']}
            </p>
        {/if}
        {if $delivery_address_field_list['EMail']}
            <p class="user-address-email">
                {$delivery_address_field_list['EMail']['UserAccountValue']}
            </p>
        {/if}
    </div>
    <div class="block">
        <label>
            <input type="radio" name="DeliveryAddress" value="OtherAddress">
            {"Deliver to another address"|i18n("design/standard/shop")}
        </label>
        <div class="block">
            {foreach $delivery_address_field_list as $delivery_address_field => $delivery_address_field_conf}
                <div class="element">
                    <label>
                        {$delivery_address_field_conf['Name']}:{if $delivery_address_field_conf['Required']}*{/if}
                    </label><div class="labelbreak"></div>
                    {switch match=$delivery_address_field_conf['Type']}
                    {case match='country_list'} 
                    {include uri='design:shop/country/edit.tpl' select_name=concat('DeliveryAddress_', $delivery_address_field) select_size=5 current_val=$delivery_address_field_conf['DefaultValue']}
                    {/case}
                    {case}
                    <input class="halfbox" type="text" name="DeliveryAddress_{$delivery_address_field}" size="20" value="{$delivery_address_field_conf['DefaultValue']|wash}" />
                    {/case}
                    {/switch}
                </div>
            {/foreach}
        </div>


        <div class="block">
            <label>
                {"Comment"|i18n("design/standard/shop")}:
            </label><div class="labelbreak"></div>
            <textarea name="Comment" cols="80" rows="5">{$comment|wash}</textarea>
        </div>


        <div class="buttonblock">
            <input class="button" type="submit" name="CancelButton" value="{"Cancel"|i18n('design/standard/shop')}" />
            <input class="defaultbutton" type="submit" name="StoreButton" value="{"Continue"|i18n( 'design/standard/shop')}" />
        </div>
    </div>

</form>

<p>
    {"All fields marked with * must be filled in."|i18n("design/standard/shop")}
</p>

