{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{"Your account information"|i18n("design/standard/shop")}</h1>

<form method="post" action={"/owshop/userregister/"|ezurl}>
    <div class="block">
        <label>
            <input type="radio" name="DeliveryAddress" value="UserAccountAddress" {if $delivery_address_choice|eq('UserAccountAddress')}checked="checked"{/if} />
            {"Deliver to this address"|i18n("design/standard/shop")}
        </label>
        {if and($delivery_address_choice|eq('UserAccountAddress'), $input_error)}
            <div class="warning">
                <p>
                    {"Input did not validate, complete your profile or use a custom delivery address"|i18n("design/standard/shop")}
                </p>
            </div>

        {/if}
        <p>
            <b>{"Customer"|i18n("design/standard/shop")}</b>
        </p>
        <p>
            {foreach $user_shop_account.field_list.customer as $field}
                {if $user_shop_account.user_account_info.$field}
                    {$user_shop_account.field_configuration.$field.name}: {$user_shop_account.user_account_info.$field|wash}<br />
                {/if}
            {/foreach}
        </p>
        <p>
            <b>{"Address"|i18n("design/standard/shop")}</b>
        </p>
        <p>
            {foreach $user_shop_account.field_list.delivery_address as $field}
                {if $user_shop_account.user_account_info.$field}
                    {$user_shop_account.field_configuration.$field.name}: {$user_shop_account.user_account_info.$field|wash}<br />
                {/if}
            {/foreach}
        </p>
    </div>
    <div class="block">
        <label>
            <input type="radio" name="DeliveryAddress" value="OtherAddress" {if $delivery_address_choice|eq('OtherAddress')}checked="checked"{/if} />
            {"Deliver to another address"|i18n("design/standard/shop")}
        </label>
        {if and($delivery_address_choice|eq('OtherAddress'), $input_error)}
            <div class="warning">
                <p>
                    {"Input did not validate, all fields marked with * must be filled in"|i18n("design/standard/shop")}
                </p>
            </div>

        {/if}
        <div class="block">
            {foreach $user_shop_account['field_list']['all'] as $field}
                <div class="element">
                    <label>
                        {$user_shop_account['field_configuration'][$field]['name']}:{if $user_shop_account['field_configuration'][$field]['required']}*{/if}
                    </label><div class="labelbreak"></div>
                    {switch match=$user_shop_account['field_configuration'][$field]['type']}
                    {case match='country_list'} 
                    {include uri='design:shop/country/edit.tpl' select_name=concat('DeliveryAddress_', $field) select_size=5 current_val=$user_shop_account['default_values'][$field]}
                    {/case}
                    {case}
                    <input class="halfbox" type="text" name="DeliveryAddress_{$field}" size="20" value="{$user_shop_account['default_values'][$field]|wash}" />
                    {/case}
                    {/switch}
                </div>
            {/foreach}
        </div>


        <div class="block">
            <label>
                {"Comment"|i18n("design/standard/shop")}:
            </label><div class="labelbreak"></div>
            <textarea name="Comment" cols="80" rows="5">{$comment|wash}</textarea>
        </div>


        <div class="buttonblock">
            <input class="button" type="submit" name="CancelButton" value="{"Cancel"|i18n('design/standard/shop')}" />
            <input class="defaultbutton" type="submit" name="StoreButton" value="{"Continue"|i18n( 'design/standard/shop')}" />
        </div>
    </div>

</form>

<p>
    {"All fields marked with * must be filled in."|i18n("design/standard/shop")}
</p>

